language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - backend

before_install:
  - if [[ $TRAVIS_BRANCH == "backend" ]]; then
      export SSH_KEY=deploy_key
      export IP_ADDRESS=$STAGING_IP_ADDRESS
      export APP_DIR=/home/ubuntu
      export SERVER_USER=ubuntu
    fi
  # Decrypt deploy key and add to SSH keys
  - openssl aes-256-cbc -K $encrypted_ba9faf39c0a7_key -iv $encrypted_ba9faf39c0a7_iv
    -in $SSH_KEY.enc -out ./$SSH_KEY -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./$SSH_KEY
  - echo -e "Host $IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./$SSH_KEY

script:
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: backend

after_success:
  # Reload NGINX on server
  - ssh $SERVER_USER@$IP_ADDRESS "bash -s" < "sudo systemctl reload nginx"
