language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  - APP_DIR=/home/ubuntu

before_install:
- openssl aes-256-cbc -K $encrypted_ba9faf39c0a7_key -iv $encrypted_ba9faf39c0a7_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $STAGING_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

script:
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: backend

after_success:
  - ssh ubuntu@$STAGING_IP_ADDRESS "bash -s" < "sudo systemctl reload nginx"
