language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
  - npm run build

env:
  - SERVER_IP_ADDRESS=3.90.254.42

before_install:
- openssl aes-256-cbc -K $encrypted_ba9faf39c0a7_key -iv $encrypted_ba9faf39c0a7_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: .deploy.sh
  on:
    branch: backend
